### ISSUE TITLE
Not able to set amount for bulk mode

### ISSUE THREAD

**Issue by sudojoseph** [thm/uinames#109]
I think it would be nice to be able to put in a number for bulk mode so you can get the number of names you need.

**Comment by Joseph1989** [comment]
Would like to start this

**Comment by thm** [comment]
Excuse the late response! This was possible in the past, also through the API. However, people ended up abusing this by requesting serious quantities of names, which in turn often caused things to break for everyone. I ended up capping both the API and setting a timer on the bulk option on uinames.com for that reason.
