### ISSUE TITLE
Alternative to uifaces.com

### ISSUE THREAD

**Issue by wangela** [thm/uinames#111]
It seems Caleb Ogden has [stopped supporting uifaces.com](https://twitter.com/search?q=to%3Acalebogden%20faq&src=typd) and the rights for the photos on there are questionable, as he has [received requests from the face owners](https://twitter.com/search?l=&q=to%3Acalebogden&src=typd) to be removed from his site since they didn't expect their faces to be used for whatever purposes. The selection on this site is also very limited when it comes to diversity (especially gender diversity).

[DiverseUI.com](https://diverseui.com/) and [Random User Generator](https://randomuser.me/) might be good alternatives, though the latter seems to have overlapping intent with UINames.

**Comment by wangela** [comment]
Actually, scratch Random User Generator - credits indicate that the photos were selected from uifaces.com and probably have not been updated to respect anyone who requested removal from uifaces.

**Comment by thm** [comment]
Thanks for the suggestions. I'm closing this old issue. Some time ago I've replaced uiFaces photos with photos from Unsplash: https://unsplash.com/license
