### ISSUE TITLE
Name order

### ISSUE THREAD

**Issue by jmblog** [thm/uinames#60]
On http://uinames.com/, every names are shown as *name - surname* but in many countries name order is *surname - name*.

http://en.wikipedia.org/wiki/Personal_name#Name_order

My suggestion is to add an `order` field to `names.json` like this:

```json
[
  {
    "country": "Country",
    "male": ["Male", "First", "Names"],
    "female": ["Female", "First", "Names"],
    "surnames": ["Last", "Names"],
    "order": "Western"
  },
  {etc}
]
```

What do you think?

**Comment by thm** [comment]
@jmblog I'm sorry about this. I'm looping @ClaudioAlbertin in to see if he's got some time to think this through. If not, then I'll be forced to hold off of this for now.

**Comment by jmblog** [comment]
@thm Don't worry about it. Thanks for your consideration.

**Comment by thm** [comment]
@jmblog I've updated this in the front-end. So, names obtained through [uinames.com](http://uinames.com) will be in the correct order now.

**Comment by jmblog** [comment]
@thm Great!! Thank you so much for the quick update.

**Comment by ClaudioAlbertin** [comment]
You can specify exceptions for the names of a specific "pool" (country or country/language-combination) by adding using one of the properties "exceptions" for general exceptions or "female_exceptions" and "male_exceptions" respectively for exceptions that only apply to one gender. Using exceptions you can achieve *any* modification of the names you might want. The exceptions use RegEx and take an array of a pattern and a replacement. This yet has to be documented more thoroughly.

In this specific case you simply need to add this line to all countries which name order should be switched:

    "exceptions": [["/^(.*) (.*)$/", "$2 $1"]]
