### ISSUE TITLE
Add Madagascar

### ISSUE THREAD

**Issue by Steffi3rd** [thm/uinames#78]
Lastname : 

Andria
Rakoto
Rabary
Rabe
Ravao
Ravelo
Ravo
Raza
Rasa

Firstname : 

Aiko
Aiky
Aina
Ainga
Aingo
Aintsoa
Ajo
Alidera
Alindranto
Aliotsy
Alisoa
Ambina
Ambinina
Ambinintsoa
Amboara
Ampela
Ampinga
Ampy
Anay
Andiana
Andimalala
Ando
Andoniaina
Andotiana
Andraina
Andriamampianina
Andriambato
Andriamifidy
Andriamihaja
Andriananja
Andrianilana
Andrianina
Andrianivo
Andrianjaka
Andriantafika
Andriantsoa
Andriarisoa
Andrinay
Andriniaina
Andry
Andy
Angola
Angy
Anja
Anjara
Anjarafitia
Anjaramendrika
Anjaranirina
Anjarasoa
Anjatiana
Anjavidy
Anoka
Anta
Antenaina
Antra
Antsa
Antsanala
Antsiva
Antso
Any
Arena
Arianala
Arifanja
Arimasy
Arindranto
Arinialy
Arinjara
Arinoa
Arivelo
Arivola
Aro
Aroniaina
Ary
Asandratra 
Asara
Asy
Avana
Avisoa
Avo
Avonoro
Avotiana
Avotra
Avovo

Babakely
Baholy
Bako
Bakohery
Bakoly
Bakonirina
Baliaka
Balita
Bango
Bao
Baofara
Baovola
Barijaona
Barilala
Bary
Batseba
Bazoly
Beandaza
Bebisoa
Beby
Bekoto
Bema
Benalisoa
Bendriana
Beniaina
Benja
Benjanirina
Bodoarimanga
Baobilahibihy
Bina
Biteny
Bodo
Bodohary
Bodohasina
Bodomalala
Bokonisy
Bora

Dadavy
Dafy
Dama
Dany
Dera
Dialy
Diamondra
Diary
Diavolana
Diera
Dimbinandrianina
Dimbinirina
Dimbisoa
Dimby
Dina
Dinasoa
Ditra
Doda
Domoina 
Donga
Doria

Eja
Ekena
Elabakana
Elamanjaka
Elintsoa
Elisoa
Elitiana
Embona
Entso
Eraniaina
Eva

Fahafahana
Fahasambarana
Faliarivo
Falihery
Falimampionona
Falinirina
Falisoa
Faly
Famenontsoa
Fanaiky
Fanaina
Fanaja
Fanambinantsoa
Fanantenana
Fanantenanirainy
Fanaperana
Fanasina
Fandresena
Faneva
Fanihy
Fanilo
Fanilonay
Fanirina
Fanirintsoa
Fanirisoa
Faniry
Fanja
Fanjaniaina
Fanjatiana
Fano
Fanoela
Fanomezana
Fanomezantsoa
Fanorenana
Fanova
Fara
Faramalalako
Faranirina
Farasoa
Faratiana
Fatratra
Fehinjo
Fehizoro
Felamanitra
Felana
Felantsoa
Feno
Fenodera
Fenoery
Fenohanitra
Fenohasina
Fenohery
Fenomanantsoa
Fenosoa
Fenotiana
Fetinaty
Fetra
Fetraniaina
Fety
Fiadanantsoa
Fialy
Fiambe
Fiandry
Fiaro
Fiary
Fiderana
Fidihasina
Fidimalala
Fidinirina
Fidisoa
Fidy
Fifaliana
Fiharo
Fikasana
Filamatra
Finaritra
Finiavana
Finidy
Finihavana
Finoana 
Firary
Fitahiana
Fitahina
Fitahintsoa
Fitia
Fitiavana 
Fitiana
Fitiantsoa
Fototsoa
Fy

Gaga
Gasy
Gia
Gina

Haba
Hafaliana 
Haga
Hagasoa
Haina
Haingo
Haingolalaina
Haingolalao
Haingoniaina
Haingotiana
Haino
Haja
Hajanirina
Hajarivelo
Hajasoa
Hajatahiana
Hajatiana
Halimanana
Hando
Hanintsoa
Hanitra
Hanitriniaina
Hanitriniala
Hanja
Hanta
Hantamalala
Hantaniaina
Hantanirina
Hantsa
Hantasoa
Harena
Harenamamy
Harenasoa
Harentsoa
Hariandra
Hariela
Harifara
Harifera
Harifidy
Harijaona
Harijao
Harilala
Harilandy
Harilanto
Harilila
Hariliva
Harimanitra
Harimbola
Harimisa
Harinaivo
Harinala
Harinandrianina
Harinavo
Harindra
Harindranto
Hariniaina
Hariniela
Harinirina
Harinisa
Harinivo
Harinoa
Harinony
Harinosy
Harintsoa
Harisoa
Haritiana
Harivelo
Harivola
Harivololona
Harivonjy
Harivony
Harizo
Hary
Hasimboahirana
Hasimbola
Hasina
Hasinandrianina
Hasindrazana
Hasiniaina
Hasiniony
Hasintsifa
Hasintsoa
Hasitiana
Hejo
Helisoa
Hendriniaina
Hendry
Henika
Henikaja
Henintsoa
Henisoa
Henitsoa
Heraina
Herihajaina
Herilala
Herilalaina
Herilaza
Herimalala
Herimamy
Herimena
Herinambinina
Herinandriana
Herinantenaina
Herinarivo
Heriniaina
Heriniony
Herinirina
Herinjaka
Herintsitohaina
Herintsoa
Herisetra
Herisoa
Herisolo
Heritiana
Heritoavina
Heritsitohaina
Heritsoa
Herivelo
Herivola
Herizo
Hery
Hetiarivony
Hiangotiana
Hiarivelo
Hirantsoa
Hirasoa
Hobialy
Hobiana
Hobiniaina
Hobinjanahary
Hobisoa
Hoby
Hoelatiana
Hova
Hovanirina
Holifanja
Holisoa
Holitiana
Holy
Honty

Ialintsoa
Ialivelo
Ialy
Iandry
Iangola
Iangolatiana
Iangotiana
Iangy
Ianja
Iarantsoa
Iarinirina
Iarinony
Iarintsoa
Iarivo
Iarivolana
Iarivolaniaina
Iarivosahala
Iavo
Iavotiana
Ibonia
Ifaliana
Ihaja
Ihandry
Ihantana
Iharantsoa
Ihary
Ihasinanjaka
Ihasinjaka
Iholy
Ikala
Ikandrina
Ikotoroa
Ikotokely
Ilaidama
Ilo
Imahery
Imaso
Imasy
Imboasalama
Imboasoa
Ingahimatoabe
Ioly
Iombonantsoa
Iony
Iraina
Iriana
Irianja
Iriela
Itokiana
Ivo

Josia
Jao
Jaojoby
Jaona
Jaonary
Jaonasy
Jaosolo
Jaotiana
Jaozandry
Jary
Jedy
Jery
Jihy
Johary
Joda
Joharinaly
Johary
Jonihary
Joro

Kajy
Kalasy
Kaliana
Kalo
Kaloina
Kaloy
Kanto
Kemba
Ketaka
Ketrika
Kiady
Kintana
Kolo
Koloina
Koly
Koriana
Koto
Kony
Kerty

Lahatra
Lahisoa
Laidama
Laingo
Lala
Lalaina
Lalainasoa
Lalandy
Lalanirina
Lalao 
Lalaonirina
Lalatiana
Laly
Landivola
Landy
Lanja
Lanto 
Lantoharifetra
Lantoharisoa
Lantoniaina
Lantonirina
Lantosoa
Lavorary
Laza
Lazamaniraka
Lebody 
Lefa
Lemazava
Lezo
Liana
Lianala
Liantsoa
Lisy 
Lita
Liva
Lofo
Loharano 
Lova 
Lovanandrianina
Lovanirina
Lovasoa
Lovatiana

Maeva
Maevasoa
Magneva
Mahaleo
Mahaliana
Mahandry
Mahanina
Maharavo
Maharo
Mahary
Mahasetra
Mahatana
Mahatia
Mahatsangy
Mahavita
Mahazina
Mahefa
Mahefasoa
Mahefarifetr
Maheriniaina
Maherisoa
Mahery
Mahiantsoa
Mahitsy
Maholy
Mahony
Malala
Malalasoa
Malalatiana
Malanto
Mamihaja
Mamihajasoa
Mamihasina
Mamihery
Mamilaza
Maminiaiko
Maminiaina
Maminirina
Maminjaka
Maminosoa
Mamiratra
Marina
Mamisoa
Mamitiana
Mamonjisoa
Mamonjy
Mampianina
Mampionona
Mamy 
Manalina
Manalintsoa
Manambina
Manampisoa
Mananjara
Manantsoa
Manarivo
Manda
Mandamina
Mandranto
Mandresy
Mandrindra
Maneva
Manevasoa
Manganirina
Mangatiana
Manitra
Manitriniaina
Manitriniala
Manitsoa
Manja
Manjaka
Manoa
Manohiaina
Manohisoa
Manosoa
Manovontsoa
Manovosoa
Marina
Maro
Masindray
Masoandro
Matsilo
Mavo
Mbato
Mbelo
Mbinina
Mboahangy
Mboara
Mboarasoa
Mbola
Mbolanirina
Mbolasoa
Mbolatiana
Mendrika
Mendrikay
Mendrintsoa
Menja
Mety
Meva
Mevasoa
Miadana
Miadantsoa
Miady
Miahy
Miaina
Mialitiana
Mialo
Mialy
Miando
Miandra
Miandrasoa
Miandrisoa
Miandry
Miangaly
Miangola
Miangoty
Miangy
Mianja
Mianoka
Miantsa
Miaramanana
Miarana
Miarantsoa
Miarintsoa
Miarisoa
Miaritiana
Miarivola
Miaro
Miary
Miasy
Michela
Mihaja
Mihamina
Mihanta
Mihantasoa
Miarihasina
Miharinjato
Miharivelo
Miharizo
Mihary
Mihasoa
Mihatia
Mihobisoa
Mihoby
Mija
Mijoro
Mika
Milamina
Milanto
Mino
Minoarisoa
Minosoa
Miora
Miorika
Miotisoa
Mioty
Mira
Mirado
Mirana
Miranto
Mirantsoa
Mirasoa
Mirija
Mirindra
Misa
Misaina
Misandratra
Misetra
Mitia
Mitiasoa
Mitsiky
Miza
Monja
Monjy
Moramanana
Mpanjato
Mparany

Nafeno
Naina
Naivo
Naivosoa
Nahary
Najaina
Naka
Nalilala
Naliniriana
Nalisoa
Naly
Nambinina
Nampiana
Nampiona
Nampoina
Nandivola
Nandrasana
Nandriana
Nandrianina
Nanja
Nanta
Nantenaina
Narindra
Narindrasoa
Narisoa
Narivo
Narivony
Nary
Nasaina
Nasandratra
Nasolo
Natanaela
Navalona
Ndiasana
Ndimbisoa
Ndimby
Ndranto
Ndrema
Ndretsa
Ndriana
Ndrianja
Ndroso
Nekena
Niaina
Niary
Nija
Niniana
Niriantsa
Nirina
Nirintsoa
Nirisoa
Niry
Nisa
Nisainana
Nivo
Nivohanta
Nivomboahangy
Nivonjanahary
Nivosoa
Nizaka
Njaka
Njakaniaina
Njakasoa
Njakatiana
Njara
Njaramalala
Njarasoa
Njaratiana
Njato
Njava
Njila
Njiva
Njivatiana
Nofy
Nohary
Nombana
Nomen'iavo
Nomeny
Nomena
Nomenaniaina
Nomenjanahary
Noro
Noroanja
Norosoa
Norotiana
Nosy
Notiavina
Ntsoa
Ny antsa
Ny antsiva
Ny anjarasoa
Ny hasina
Ny hira
Ny iangotiana
Ny ony
Ny tony

Oelisoa
Oliseheno
Olinirina
Oly
Ombana
Onasoa
Onimamy
Onimilanto
Onintsoa
Onisoa
Onitiana
Onja
Onjalalaina
Ony
Orimbato

Patsy
Pelake
Pendo
Peta
Petrabolana

Rabozaka
Rado
Radonandrasana
Radonirina
Radoniaina
Radosoa
Raitra
Raivo
Raivosoa
Rajaona
Rajery
Rajo
Ralay
Ranja
Ranjalahy
Ranjatiana
Ranjatohery
Ranoro
Ranto
Raomy
Raony
Rary
Raseta
Ravaka
Ravotany
Razay
Redy
Rehareha
Rejo
Remenabila
Reniala
Renjy
Retovognae
Riaka
Rialy
Riana
Rianala
Riantsoa
Rify
Rija
Rima
Rina
Rinantsoa
Rindra
Rindja
Rindraniaina
Rindranirina
Rindratiana
Ririva
Rivo
Rivohery
Rivolala
Rivonala
Rivoniaina
Rivonirina
Rivosoa
Robo
Roby
Rohintsoa
Rohy
Rojo
Rondro
Rondronirina Herivelona
Rotsy
Rova
Rovalala
Rovasoa
Ryanto

Safidiko
Safidy
Sahala
Sahaza
Sahitia
Sahitsy
Sahoby
Saholy
Sahondra
Salala
Salohy
Sambatra
Sanda
Sandratra
Sandy
Sanjy
Santatra
Santiona
Saotra
Saovololona
Saranto
Sariaka
Sarika
Sarindra
Sarobidy
Sata
Sedera
Sedra
Seheno
Sendra
Seta
Setra
Silo
Sinasoa
Sitraka
Soa
Soafinaritra
Soafaniry
Soafara
Soamiangaly
Soamiely
Soanala
Soananahary
Soanavalona
Soandriaka
Soaniriko
Soanja
Soarimanga
Soary
Soatia
Soatina
Soamazava
Soja
Solo
Solofo
Solofoarivelo
Solofohery
Solohery
Solonomenjanahary
Solotiana
Soly
Sonia

Tafika 
Tafita 
Tafitasoa
Tahadray
Tahina 
Tahiry 
Takalo
Tambatra
Tambinirina
Tamby 
Tamisoa
Tanjona
Tantely 
Tanteraka 
Taramasoandro
Taratra
Tarika
Tatamo
Tefiniaina
Tefy
Telina
Tendry
Tenompitia
Teza
Tiafina
Tiaina
Tiana
Tianamalala
Tiary
Tiavina
Tina
Tinasoa
Tinda
Toandro
Toavina
Todisoa
Todizara
Tody
Tojo
Tojohafaliana
Tojohery
Tojolafatra
Tojomanana
Tojoniaina
Tojonirina
Tojosoa
Tokiharimanitra
Tokiniaina
Toky
Tolojanahary
Tolojaona
Tolotra
Tolotriniavo
Tomefisoa
Tompoina
Tongasoa
Tonihasina
Tony
Tosy
Tovo
Tovohery
Tovojanahary
Tovojay
Trema
Trimo
Tsaina
Tsakoraiky
Tsalama
Tsangy
Tsanta
Tsaraleha
Tsaramandresy
Tsarasata
Tsaratamb
Tsarona
Tsiafoy
Tsialainkery
Tsiaro
Tsidy
Tsiferana
Tsifoina
Tsihoarana
Tsiky
Tsilavina
Tsilavo
Tsilavohery
Tsima
Tsimba
Tsimiamboho
Tsingory
Tsioritsoa
Tsiory
Tsirava
Tsiresy
Tsiriarivelo
Tsirihanitra
Tsiriry
Tsiry
Tsitoaniaina
Tsitohae
Tsitohaina
Tsitohatsy
Tsizaraina
Tsirota
Tsoa

Vahambola
Vahatra
Vahinala
Vahisoa
Vaingoka
Vakoka
Valiha
Valimpitia
Valintiana
Valisoa
Vania
Vaniala
Vaninala
Vanona
Vanondahy
Vanontiana
Vaonala
Vaosoa
Vaosolo
Vatosoa 
Vatra
Vatsy
Vazo
Vero
Verohanta
Veromanitra
Verotiana
Vimbina
Vina
Vivato
Vivy
Voahangy
Voahary
Voahirana
Voara
Voatsasie
Voatse
Vokatra
Vola 
Volamasoandro
Volamena 
Volana 
Volantsoa
Volarivony
Volasoa
Volatiana
Volatsara
Vololona
Vonifanja
Vonihanitra
Vonimanitra
Vonimbola
Voninahitra 
Vonisa
Vonjy
Vony

Zafilahy
Zafimaharavo
Zafitsiory
Zaimalala
Zaka
Zakaina
Zakara
Zanoariso
Zaraniaina
Zarapitiavana
Zara
Zarasoa
Zaratiana
Zarisoa
Zava
Zina
Zinaha
Ziona
Zivasoa
Zo 
Zoelisoa
Zoely
Zohery
Zoly
Zonahery
Zoniaina
Zoto

**Comment by thm** [comment]
You can add names to `/names.json` using the following format:
```
[
  {
    "country": "Country",
    "male": ["Male", "First", "Names"],
    "female": ["Female", "First", "Names"],
    "surnames": ["Last", "Names"]
  },
  {etc}
]
```

To guarantee implementation please make sure you read the `readme.md` file. For example, I'm not seeing 'female' and 'male' first names above, only 'first names', which wouldn't work.
